// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktqkzvbmulsqorfiwulz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_HdTQUzDZgh-ySQvrUNT5AA_6EWLdMnv";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

//check if supabase is configured properly
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Supabase is not configured properly. Please check your environment variables.");
}


export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});